### ISSUE TITLE
HIDL has been replaced to AIDL

### ISSUE THREAD

**Issue by Freed-Wu** [rubberduck203/aosp-vim#3]
>  HAL interface definition language or HIDL ... As of Android 10, HIDL is deprecated and Android is migrating to use AIDL everywhere.

See <https://source.android.com/docs/core/architecture/hidl> and <https://source.android.com/docs/core/architecture/aidl>.

**Comment by rubberduck203** [comment]
Ok. Good to know, but it’s unclear to me what the issue is here and what you’re asking for.

**Comment by Freed-Wu** [comment]
Oh, sorry. Can we provide `ftdetect/*.vim` for AIDL? Its syntax should be like java.

**Comment by Freed-Wu** [comment]
Oh, sorry again, I found vim has built-in [`aidl.vim`](https://github.com/vim/vim/blob/master/runtime/syntax/aidl.vim).

**Comment by rubberduck203** [comment]
No worries at all. I was just a little confused. I’m glad you found a solution. I’m going to leave this repo as is because I’m sure there are still folks using older versions and although it’s been deprecated, it’s not been removed yet. 

I will likely mark this repo as archived in the near future though, so thank you for bringing this to my attention.
